<?php

namespace Apex\ApexScoreCardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * roundGolferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class roundGolferRepository extends EntityRepository
{
}
