apex_score_homepage:
    pattern:  /
    defaults: { _controller: ApexScoreBundle:App:index }

ApexScoreBundle_course:
    resource: "@ApexScoreBundle/Resources/config/routing/course.yml"
    prefix: /course

ApexScoreBundle_hole:
    resource: "@ApexScoreBundle/Resources/config/routing/hole.yml"
    prefix: /hole

ApexScoreBundle_round:
    resource: "@ApexScoreBundle/Resources/config/routing/round.yml"
    prefix: /round

ApexScoreBundle_golfer:
    resource: "@ApexScoreBundle/Resources/config/routing/golfer.yml"
    prefix: /golfer

ApexScoreBundle_roundGolfer:
    resource: "@ApexScoreBundle/Resources/config/routing/roundGolfer.yml"
    prefix: /roundGolfer
    
ApexScoreBundle_scoreGolfer:
    resource: "@ApexScoreBundle/Resources/config/routing/roundScore.yml"
    prefix: /roundScore

ApexScoreBundle_app:
    resource: "@ApexScoreBundle/Resources/config/routing/app.yml"
    prefix: /app

ApexScoreBundle_site:
    resource: "@ApexScoreBundle/Resources/config/routing/site.yml"
    prefix: /site

GlobalJs:
    pattern: /js/global.js
    defaults: { _controller: ApexScoreBundle:Default:globaljs, _format: js }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
login_check:
    pattern: /login_check
    defaults: { _controller : ApexScoreBundle:App:index }