#apex_score_homepage:
#    pattern:  /
#    defaults: { _controller: ApexScoreBundle:Default:login }


ApexScoreBundle_course:
    resource: "@ApexScoreBundle/Resources/config/routing/course.yml"
    prefix: /course

ApexScoreBundle_hole:
    resource: "@ApexScoreBundle/Resources/config/routing/hole.yml"
    prefix: /hole

ApexScoreBundle_round:
    resource: "@ApexScoreBundle/Resources/config/routing/round.yml"
    prefix: /round

ApexScoreBundle_golfer:
    resource: "@ApexScoreBundle/Resources/config/routing/golfer.yml"
    prefix: /golfer

ApexScoreBundle_roundGolfer:
    resource: "@ApexScoreBundle/Resources/config/routing/roundGolfer.yml"
    prefix: /roundGolfer

ApexScoreBundle_app:
    resource: "@ApexScoreBundle/Resources/config/routing/app.yml"
    prefix: /app

GlobalJs:
    pattern: /js/global.js
    defaults: { _controller: ApexScoreBundle:Default:globaljs, _format: js }


#apex_score_app: 
#    pattern: /App
#    defaults: { _controller: ApexScoreBundle:App:index }

#login:
#    pattern: /login
#    defaults: { _controller: ApexScoreBundle:Default:login }

#login_check:
#    pattern: /login_check
    
#admin:
#    pattern: /admin/poo
#    defaults: { _controller: "ApexScoreBundle:app:index" }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
    