parameters:
#    apex_score.example.class: Apex\ApexScoreCardBundle\Example

services:
#    apex_score.example:
#        class: %apex_score.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
