parameters:
#    apex_score.example.class: Apex\ApexScoreCardBundle\Example

services:
    apex_score.registration.form.type:
        class: Apex\ApexScoreCardBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: apex_score_registration }
