course:
    pattern:  /
    defaults: { _controller: "ApexScoreBundle:Course:index" }

course_show:
    pattern:  /{id}/show
    defaults: { _controller: "ApexScoreBundle:Course:show" }

course_new:
    pattern:  /new
    defaults: { _controller: "ApexScoreBundle:Course:new" }

course_create:
    pattern:  /create
    defaults: { _controller: "ApexScoreBundle:Course:create" }
    requirements: { _method: post }

course_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ApexScoreBundle:Course:edit" }

course_update:
    pattern:  /{id}/update
    defaults: { _controller: "ApexScoreBundle:Course:update" }
    requirements: { _method: post }

course_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ApexScoreBundle:Course:delete" }
    requirements: { _method: post }

course_json_get:
    pattern: /json/show/course
    defaults: { _controller: "ApexScoreBundle:Course:getCourseList" }
    requirements: { _method: post|get }
    
course_json_get_data:
    pattern: /json/get/course/data
    defaults: { _controller: "ApexScoreBundle:Course:getCourseData" }
    requirements: { _method: post }
    
course_json_set:
    pattern: /json/set/course/data
    defaults: { _controller: "ApexScoreBundle:Course:saveCourseData" }
    requirements: { _method: post|get }